version: "3.8"

services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatwoot_dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - internal

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=chatwoot_dev
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_LOG_LEVEL=debug
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    networks:
      - internal

  chatwoot:
    image: chatwoot/chatwoot:latest
    command: "bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      INSTALLATION_ENV: docker
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: chatwoot_dev
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: b8e62f4473e17c7227bbd7bcc172d79a33ae2b1bed88c78e6f48d9c429666c683263b7177c2760f12e78c85ec096f82de308b502b0a7072289c1d84f8d5f6393
      FRONTEND_URL: http://localhost:3000
      DEFAULT_LOCALE: es
    volumes:
      - ./chatwoot-data:/app/storage
    depends_on:
      - postgres
      - redis
    networks:
      - internal

networks:
  internal:
    driver: bridge
